version: '1.0.0'

# Uncomment environment, if you want to use debug mode.

services:
  web:
    build: .
    ports:
      - '8899:8899'
    volumes:
      - '.:/usr/src/app'
    command: air
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:16
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data

volumes:
  postgres-db:
  redis-data:
